version: 2
updates:
  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: weekly
      time: '06:00'
      timezone: 'Europe/Amsterdam'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '06:00'
      timezone: 'Europe/Amsterdam'
